packages:
  - '.'

blockExoticSubdeps: false

overrides:
  '@remix-run/router': ^1.23.2
  lodash: ^4.18.0
  react-router: ^6.30.2
  serialize-javascript: ^7.0.5
  flatted: ^3.4.0
  immutable: ^5.1.5
  dompurify: ^3.4.0
  picomatch@^2: ~2.3.2
  picomatch@^4: ^4.0.4
  yaml: ^2.8.3
  minimatch@^3: ~3.1.4
  minimatch@^9: ~10.2.0
  minimatch@^10: ^10.2.3
  undici: ^7.24.0
  brace-expansion@^1: ^1.1.13
  brace-expansion@^5: ^5.0.5
  '@types/react': ^18.3.28
  '@types/react-dom': ^18.3.7
  uuid: ^14.0.0
  '@tootallnate/once': '>=3.0.1'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
