name: Bundle Types

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

jobs:
  bundle-types:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 (2026-01-09)
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/bundle-types@d4bf687e0b40ddb26b4212e9c2b06dfb491e28b6 # bundle-types/v1.0.4 (2026-07-13)
        with:
          entry-point: ./src/exposedComponents/types.ts
          ts-config: ./tsconfig-for-bundle-types.json
          node-version: '22'
