name: Bundle Types

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

jobs:
  bundle-types:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3 (2026-01-09)
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/bundle-types@ad81bca30a8f98102741e1e6b0b6898a265ad691 # bundle-types/v1.0.3 (2026-02-24)
        with:
          entry-point: ./src/exposedComponents/types.ts
          ts-config: ./tsconfig-for-bundle-types.json
          node-version: '22'
