name: CI

on:
  workflow_dispatch:
    inputs:
      skip-grafana-dev-image:
        description: Skip the grafana dev image e2e test
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  CI:
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      run-playwright: false
      run-playwright-docker: true
      run-playwright-with-skip-grafana-dev-image: ${{ inputs.skip-grafana-dev-image || false }}
      upload-playwright-artifacts: true
      playwright-report-path: e2e/test-reports/
      playwright-docker-compose-file: docker-compose.yaml
      playwright-grafana-url: http://localhost:3001
