name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  CI:
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v7.0.0
    with:
      run-playwright: false
      run-playwright-docker: true
      upload-playwright-artifacts: true # IMPORTANT: we must ensure there are no unmasked secrets in the E2E tests
      run-playwright-with-skip-grafana-dev-image: true
      playwright-report-path: e2e/test-reports/
      playwright-docker-compose-file: devenv/docker-compose.e2e.yaml
      playwright-grafana-url: http://localhost:3030
