name: Build and release main to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only docs files have been changed
      - 'docs/**'
      - '**.md'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b
        with:
          vault_instance: ops
          common_secrets: |
            token=plugins/sign-plugin-access-policy-token:token
          export_env: false
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Call shared build action
        uses: ./.github/actions/build
        with:
          policy_token: ${{ fromJSON(steps.get-secrets.outputs.secrets).token }}
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download zip
        uses: actions/download-artifact@v4
        with:
          name: grafana-exploretraces-app-latest.zip
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            GCP_UPLOAD_ARTIFACTS_KEY=grafana/integration-artifacts-uploader-service-account:'credentials.json'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}
      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./grafana-exploretraces-app-latest.zip
          destination: 'integration-artifacts/grafana-exploretraces-app/'
          parent: false
